### ISSUE TITLE
Some URLs (for older development applications) no longer work

### ISSUE THREAD

**Issue by MichaelBone** [planningalerts-scrapers/yorke_peninsula_council_sa_development_applications#2]
URLs that previously jumped to development application details no longer work.  For example, the following URL previously jumped to the details for development application 544.2001.00001241.001:

https://yorke.sa.gov.au/development/development-information/development-register/entry/7413005/?pagenum=3

As of January 2019 this URL instead falls back to a search page that shows what appears to be all development applications.

Instead, the URL to access development application 544.2001.00001241.001 is now:

https://yorke.sa.gov.au/development/development-information/development-register/entry/7428382/

(Although the URLs for some newer development applications have not changed, and still work.)

**Comment by LoveMyData** [comment]
Fixed by PR https://github.com/planningalerts-scrapers/yorke_peninsula_council_sa_development_applications/pull/1
